version: '3.7'

services:
  database:
    image: postgres:11.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=irisdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
    expose:
      - '5432'
  api:
    build:
      context: .
      dockerfile: ./services/public-api/Dockerfile.dev
    volumes:
      - './services/public-api:/usr/src/app/services/public-api'
      - './@iris:/usr/src/app/@iris'
    ports:
      - 4000:4000
